//variables
// let name="Smriti";
// let age="20";
// age = "21";
// console.log(name , age);

// const account =1234;
// account =4567;
// console.log(account);


// Let age="20";
// Let age="21";
// console.log(age);


// var a=10;
// var a=20;
// console.log(a);



// let a =10;
// let b=2.36;
// console.log(a,b);

// //string
// let c="smriti";
// let d="she is nice";
// console.log(c,d);

//boolean
// let login=true;
// let F=false;
// console.log(login,F);


// let user;
// console.log(user);


// //bigint
// let num=232163782617889028388n;
// console.log(num);


//symbol
const id1=Symbol("id");
const id2=Symbol("id");
console.log(id2==id1);

//non primitive data type
//array
let arr=[10,20,11,"smriti",true];
console.log(arr);


let user={
    firstName:"Smriti",
    lastName:"Singh",
    age:20,
};
console.log(user);



// function add(){
//     console.log("Hello");
// }
// add();

//we can store a function in variable in js
let s=function add(){
    console.log("hello");
}
console.log(s());


//TYPE OF NUMBER
let a =10;
let b="smriti";
console.log(typeof a, typeof b);

//null
let weather=null;
console.log(typeof weather);
//biggest of js it says type of null is object not null

//for all non primitive data types the type of of every data type is object
